name: Check

on:
  push:
    branches: [master]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - name: Flake checks (clippy, rustfmt)
        run: nix flake check -L
      - name: Build
        run: nix build -L
